@section('footer')
<section id="footer">
	<div class="social soci_movil">
	    <a target="_blank" href="https://www.facebook.com/ZignumMezcal" class="socicon" onclick="ga('send', 'event', 'Footer','RS', 'Facebook');">b</a>
	    <a target="_blank" href="https://twitter.com/zignummezcal" class="socicon" onclick="ga('send', 'event', 'Footer','RS', 'Twitter');">a</a>
	    <a target="_blank" href="https://vine.co/u/1147306442412412928" class="socicon" onclick="ga('send', 'event', 'Footer','RS', 'Vine');">u</a>
	 </div>
	<div id="footer_top">
		<div id="footer_twitter" class="middle_center">
			<button href="" id="popup_twitter" onclick="ga('send', 'event', 'Footer','Share Twitter');">a<span>#ZIGNUMMEZCAL</span></button>
		</div>
		<div id="footer_face" class="middle_center">
			<iframe src="//www.facebook.com/plugins/like.php?href=http%3A%2F%2Fzignummezcal.com&amp;width&amp;layout=button_count&amp;action=like&amp;show_faces=false&amp;share=false&amp;height=21" scrolling="no" frameborder="0" style="border:none; overflow:hidden; height:21px;" allowTransparency="true"  onclick="ga('send', 'event', 'Footer','Like');"></iframe>
		</div>
	</div>
	<div id="footer_bottom">
		<div>
			<a id="aviso" href="#" onclick="click_aviso(), ga('send', 'event', 'Footer','Ligas', 'Aviso de Privacidad')">{{$menu[9]}}</a>
			<a id="terminos" href="#" onclick="click_term(), ga('send', 'event', 'Footer','Ligas', 'Terminos y Condiciones')">{{$menu[10]}}</a>
			<a id ="contacto" href="/contacto" onclick="ga('send', 'event', 'Footer','Contacto')">{{$menu[11]}}</a>
		</div>
		<div>
			<p id="evita">{{$menu[12]}}</p>
			<a target="blank" href="http://www.alcoholinformate.org.mx" onclick="ga('send', 'event', 'Footer','Ligas', 'Alcoholinformate')">www.alcoholinformate.org.mx</a>
		</div>
	</div>
</section>
<section id="avi" class="lbox">
	<img id="Av" class="exitAvTm" onclick="exitAvTm()" src="/zignum/public/img/btn-cerrarlightbox.jpg">
	<p><b>POLÍTICA DE PRIVACIDAD DEL SITIO WEB (AVISO DE PRIVACIDAD):</b>
CASA ARMANDO GUILLERMO PRIETO, S.A. DE C.V. (en lo sucesivo “CAGP”) esta comprometido a proteger y respetar su privacidad. Esta Política de Privacidad y/o Aviso de Privacidad (junto con los Términos y Condiciones de Uso del Sitio Web y la Política sobre Cookies e IP’s) son los que gobiernan el uso y las finalidades de la información recopilada sobre Usted. Por favor lea lo siguiente para entender nuestros puntos de vista y prácticas respecto a sus datos personales y cómo vamos a tratarlos. Aunque estamos comprometidos a mantener su seguridad y confianza en todas nuestras actividades con Usted, esta Política de Privacidad no rige nuestra recopilación y/o el uso de sus datos a través de canales distintos del presente Sitio Web. 
Por favor salga de este Sitio Web de inmediato si Usted no acepta esta Política y/o Aviso de Privacidad, o bien si no tiene la edad legal para consumir bebidas alcohólicas (como se define en los Términos y Condiciones de Uso del Sitio Web) en el país u otro territorio en el que se encuentra o está accediendo a nuestro Sitio en un país u otro territorio donde no se permite el uso de nuestro Sitio.
CAGP con domicilio en Periférico Sur No. 4829, Interior 604, Col. Parques del Pedregal, Del. Tlalpan, Ciudad de México, Distrito Federal, México, le informa que puede obtener, transferir, almacenar y hacer uso de los datos personales que nos proporcione a través del presente Sitio Web, mismos que serán utilizados exclusivamente para acceder a este Sitio Web, así como en su caso, para efectos de ofrecerle publicidad y aquellos servicios que se llegaren a ofrecer y/o prestar en este Sitio Web; así como para otras actividades cuyo acceso exija que el Usuario esté registrado, por lo tanto, sus datos serán utilizados con las siguientes finalidades:
	•	Ingresar al presente Sitio Web.
	•	En su caso, registrar y atender sus solicitudes de reservación y/o compra de nuestros productos.
	•	En su caso, cobro y facturación de los productos y servicios adquiridos.
	•	Atender sus consultas y sugerencias.
	•	Hacer de su conocimiento, promociones, concursos, certámenes y actividades organizadas por CAGP así como sus empresas subsidiarias y/o afiliadas y/o relacionadas.
	•	Documentar sus visitas o eventos.
	•	Realizar encuestas de satisfacción.
	•	Suscribirse a nuestro boletín informativo.
	•	Informarle acerca de nuestros eventos.
	•	Mantener el control de las personas (Usuarios) que acceden al presente Sitio Web.
	•	Participar en la investigación, promoción y comercialización de los servicios y/o productos; por lo que podrán ser puestos a disposición de empresas relacionadas corporativamente y/o contractualmente con CAGP.
	•	El país correcto u otro territorio en el que Usted se encuentra y/o está accediendo al Sitio Web; así como su fecha de nacimiento correcta, lo que requerimos que Usted envíe con precisión para asegurarnos que no se acceda a este Sitio Web si Usted no tiene una edad legal para consumir bebidas alcohólicas en el país o territorio en el que se encuentra o está accediendo a nuestro Sitio Web.
Le informamos que es posible que al asistir a los eventos de CAGP tomemos fotografías y que las mismas sean compartidas en medios de comunicación y redes sociales.
CAGP es el responsable de los datos personales que le recaban y por lo tanto realiza el tratamiento de sus datos personales de conformidad con los principios de licitud, consentimiento, información, calidad, finalidad, lealtad, proporcionalidad y responsabilidad, en términos de lo dispuesto por la Ley Federal de Protección de Datos Personales en Posesión de los Particulares y su Reglamento (en lo sucesivo la “Ley”).
Con la finalidad de impedir el acceso y revelación no autorizada, mantener la exactitud de los datos personales y garantizar la utilización correcta de la información, CAGP utiliza los procedimientos físicos, tecnológicos y administrativos apropiados para proteger la información que recaba.
La información personal que nos ha proporcionado se guarda en bases de datos controladas y con acceso limitado de conformidad con la Ley.
Usted podrá ejercer sus derechos de acceso, rectificación, cancelación y/u oposición, también conocidos como “Derechos ARCO”, así como la revocación de su consentimiento a la siguiente dirección de correo electrónico:
<a href="mailto:contacto@agpch.mx">contacto@agpch.mx</a>
CAGP pone a su disposición el procedimiento por el cual puede ejercer sus Derechos ARCO y revocación del consentimiento en el domicilio para oír y recibir notificaciones antes indiciado.
Hacemos de su conocimiento que CAGP se abstendrá de vender, arrendar y/o transferir sus datos personales. Únicamente compartirá su información personal en los siguientes supuestos:
a) Con empresas con las que sostenga una relación corporativa y/o contractual;
b) En su caso, con las instituciones bancarias que sean utilizadas para compra de nuestros productos.
En virtud de lo anterior las personas a las que se les realice la transferencia de datos personales no podrán utilizar la información proporcionada por CAGP de manera diversa a la establecida en el presente Aviso. Estas transferencias de datos serán realizadas con todas las medidas de seguridad apropiadas, de conformidad con los principios contenidos en la Ley.
Si hubiere una vulneración de seguridad en cualquier fase del tratamiento de sus datos personales, CAGP por correo electrónico a través de la figura del responsable, hará de su conocimiento el suceso de vulneración de seguridad de manera inmediata, para que pueda tomar las medidas necesarias correspondientes para la defensa de sus derechos. En caso de no contar con su correo electrónico, la notificación se publicará en el presente Sitio Web.
Con objeto de que pueda limitar el uso y divulgación de su información personal, Usted cuenta con los siguientes medios:
a) Inscripción en el Registro Público de Consumidores y/o en el Registro Público de Usuarios para evitar publicidad, los cuales están a cargo de la Procuraduría Federal del Consumidor (“PROFECO”) y de la Comisión Nacional para la Protección y Defensa de los Usuarios de Servicios Financieros (“CONDUSEF”) respectivamente, con la finalidad de que sus datos personales no sean utilizados para recibir publicidad o promociones de empresas de bienes o servicios. Para mayor información sobre este registro, usted puede consultar los portales de Internet de la PROFECO y CONDUSEF, o bien ponerse en contacto directo con éstas.
b) Si Usted considera que su derecho a la protección de sus datos personales ha sido lesionado por alguna conducta u omisión de nuestra parte, o presume alguna violación a las disposiciones previstas en la Ley, podrá interponer su inconformidad o denuncia ante el Instituto Federal de Acceso a la Información y Protección de Datos (“IFAI”). Para mayor información, le sugerimos visitar su página oficial de Internet <a href="http://www.ifai.org.mx" target="_blanck">www.ifai.org.mx</a>.
El registro en el presente Sitio Web exige que los datos sean facilitados de forma veraz y completa, dichos datos se actualizarán a través de su cooperación. Si los datos personales que nos llegue a proporcionar fueran incompletos o inexactos o no se actualizan en tiempo, CAGP por ese solo hecho, quedará liberado de cualquier responsabilidad que surja a consecuencia de ello.
De conformidad con lo establecido en la legislación, una vez leído el presente Aviso de Privacidad se considerará que está Usted de acuerdo con la recopilación, tratamiento, transmisión, uso y almacenamiento antes mencionado de los datos personales proporcionados a CAGP.
CAGP se reserva el derecho a modificar el presente aviso de privacidad, mismo que se anunciará en este Sitio Web y en el domicilio antes indicado con razonable antelación a su puesta en práctica.

<a href="/formulario" onclick("download('form')")>Descargar Formulario Derechos ARCO</a>
<a href="/procedimiento" onclick("download('pros")>Descargar Procedimiento de Atención Derechos ARCO</a>

<b>POLÍTICA SOBRE COOKIES E IP’S:</b>
CAGP podrá recopilar información sobre su ordenador (incluyendo, cuando sea posible, su dirección de IP, sistema operativo y tipo de navegador) para la administración del sistema y para brindar información general a nuestros anunciantes. Se trata de datos estadísticos sobre las acciones y patrones de navegación de nuestros usuarios, y no identifica a ninguna persona. Nuestros servidores de Internet también pueden realizar un seguimiento del número de visitantes a nuestros sitios, las páginas visitadas y cuánto tiempo permanecieron. Ninguna de esta información incluye cualquier información personal sobre Usted.
Esta política pretende informarle cómo el Sitio Web utiliza una tecnología llamada cookies y registros del servidor web. Esta política está destinada a ayudarle a tomar decisiones informadas al usar este Sitio Web. Por favor, tómese un minuto para leer y entender esta política.
¿Qué son las cookies? ¿Qué hacen?
Una cookie es un pequeño documento de texto, que a menudo incluye un identificador único anónimo. Cuando usted visita un sitio web, la computadora de ese sitio pide a su equipo permiso para guardar este archivo en una parte de su disco duro específicamente designado para las cookies.
La información recopilada a través de cookies y registros del servidor web puede incluir la fecha y hora de las visitas, las páginas visitadas y el tiempo de estancia en este Sitio Web.
Para más información sobre las cookies, busque en Internet en donde podrá  encontrar amplia información sobre las cookies y tecnologías similares. 
Consentimiento para el uso de cookies en este Sitio Web
Al continuar usando nuestro Sitio Web, se considera que dará su consentimiento para el uso de las cookies que se describen en esta política de cookies.
Bloqueo del uso de cookies
Puede bloquear el uso de cookies activando la configuración en su navegador. Por favor, visite Todo sobre Cookies donde se puede encontrar amplia información sobre el manejo de cookies y bloqueo para una amplia variedad de navegadores.
¿Qué pasa si bloqueo las cookies?
 Para utilizar ciertos servicios ofrecidos a través de nuestro Sitio Web, su navegador debe aceptar cookies. Si decide negar su consentimiento, o posteriormente bloquear las cookies, algunos aspectos de la Web pueden no funcionar correctamente y es posible que no pueda acceder a toda o parte de nuestro Sitio Web. 

Cómo utilizamos las cookies
Si el acceso a nuestro sitio Web requiere que introduzca su fecha de nacimiento y país, las cookies nos permiten recordar los datos que ha introducido, por lo que no necesitamos pedirle que vuelva a introducirlos cada vez que usted navega a una página diferente del Sitio Web.
También utilizamos "Webtrend Analytics" cookies que, junto con los archivos de registro de nuestro servidor web, nos permiten calcular el número total de personas que visitan nuestro Sitio Web y que partes son las más populares de nuestro portal. Esto nos ayuda a recopilar información para que podamos mejorar nuestro Sitio Web y servir mejor a nuestros clientes. Por lo general no guardamos ninguna información personal que usted nos proporciona en una cookie. La finalidad de las cookies Webtrend Analytics es el almacenamiento de información, como la vez que visitó el Sitio Web, y si usted lo ha visitado antes (y el sitio web que visitó antes de visitar nuestro Sitio Web).
También podemos utilizar "Social Media" cookies para personalizar su interacción con plataformas de redes sociales, como Twitter® y Facebook®, donde nuestro Sitio Web utiliza estas características. Estas cookies reconocen a los usuarios de redes sociales cuando Usted ve contenidos de redes sociales en nuestro Sitio Web. También le permiten compartir contenido rápidamente a través de los de las redes de comunicación, a través del simple uso del botón  "compartir". Utilizamos las siguientes cookies medios sociales: Twitter®, Facebook®, WebTrends®, Google Analytics®.
La mayor parte de nuestras cookies expiran dentro de los 30 días, aunque nuestras cookies  analíticas pueden persistir entre 2 y 10 años.


</p>
</section>
<section id="term" class="lbox">
	<img id="Tm" class="exitAvTm" onclick="exitAvTm()" src="/zignum/public/img/btn-cerrarlightbox.jpg">
	<p>
<b>TÉRMINOS Y CONDICIONES DEL USO DEL SITIO:</b> www.zignummezcal.com:
Los términos y condiciones aquí contenidos regulan el uso del sitio www.zignummezcal.com; así como de todas y cualquiera de las otras plataformas en línea y/o digitales, incluyendo móviles y otras aplicaciones, como son de manera enunciativa, más no limitativa, las aplicaciones de Facebook® y Twitter® (en lo sucesivo el “Sitio Web” y/o el “Sitio”) cuya  propiedad corresponde a Casa Armando Guillermo Prieto, S.A. de C.V. (en lo sucesivo “CAGP”), quien tiene su domicilio en Periférico Sur No. 4829, Interior 604, Col. Parques del Pedregal, Del. Tlalpan, C.P. 14010, Ciudad de México, Distrito Federal.
Por favor lea estos términos y condiciones de uso antes de empezar a utilizar nuestro Sitio.
Al acceder y utilizar el Sitio, y en su caso, contratar los servicios que en él se ofrecen, Usted se obliga a respetar y aceptar  todos los Términos y Condiciones de Uso, notificaciones y cláusulas de exclusión de responsabilidad, que se establecen en los presentes Términos y Condiciones de Uso. La aceptación de los Términos y Condiciones de Uso aquí previstos será un paso previo e indispensable, para la adquisición en su caso, de cualquier servicio que esté disponible en el Sitio.
CAGP se reserva el derecho de realizar cambios y/o modificaciones a los Términos y Condiciones de Uso establecidos en el Sitio que considere necesarios o convenientes en cualquier momento sin necesidad de aviso y/o notificación previa a los usuarios del Sitio. Usted podrá verificar y consultar de manera continua estos Términos y Condiciones de Uso con el objeto de conocer dichos cambios y/o modificaciones.
Este Sitio está reservado y dirigido única y exclusivamente a aquellas personas o usuarios que legalmente están permitidos por las leyes aplicables para comprar y consumir bebidas alcohólicas, en Países y territorios, donde la venta, publicidad y consumo de bebidas alcohólicas, es legal y permitido. En el caso de México, Estados Unidos Mexicanos, únicamente los usuarios mayores de edad, es decir, mayores a 18 años, son los que podrán acceder y hacer uso del Sitio.
Por favor salga de nuestro Sitio de inmediato si Usted no acepta estos Términos y Condiciones de Uso, y/o si Usted no tiene la edad legal para consumir bebidas alcohólicas en el País u otro territorio en el que se encuentra, o si Usted está accediendo a nuestro sitio en un País u otro territorio donde no se permite el uso de nuestro Sitio. 
CAGP a través del Sitio proporciona información acerca de sus productos y servicios y ofrece a Usted la posibilidad de su consulta.
Los Usuarios deberán utilizar el Sitio de forma responsable y con fines lícitos de conformidad con los presentes Términos y Condiciones de Uso. 
A continuación se enumeran de forma enunciativa mas no limita las actividades de las que el Usuario se deberá abstener en relación con el uso del Sitio: (i) Distribuir, divulgar, anunciar o publicar cualquier información o material que degrade, desprestigie, avergüence, humille o amenace a las personas; (ii) Abusar, difamar, hostigar, acusar, amenazar o de alguna otra manera infringir los derechos de otro; (iii) Distribuir, divulgar, anunciar o publicar cualquier material o información indecente que infrinja los derechos de terceros; (iv) Anunciar o enviar, o de cualquier otra forma divulgar información confidencial, secretos de negocios, ya sean industriales o comerciales u otros datos exclusivos, confidenciales y/o protegidos por cualquier ley o reglamento en México y/o en el extranjero; (v) Copiar o crear trabajos derivados de, desplegar, distribuir, otorgar bajo licencia, realizar, publicar, recrear, reproducir, vender, transferir o transmitir cualquier información, productos, servicios o software obtenidos por, desde o a través del Sitio; (vi) Vigilar o copiar cualquier contenido por medio de cualquier proceso; (vii) Participar en cualquier otra conducta que esté o que CAGP considere que está en conflicto con los Términos y Condiciones de Uso, y; (viii) En general, realizar cualquier acto en contra de la legislación vigente, la moral y las buenas costumbres.
Usted es responsable de hacer todos los arreglos necesarios para que Usted tenga acceso al Sitio. Usted también es responsable de asegurar que todas las personas que acceden al Sitio a través de su conexión a Internet son conscientes de estos Términos y Condiciones de Uso, y que cumplan con ellos.
INFORMACIÓN ACERCA DE USTED Y SUS VISITAS A NUESTRO SITIO Y EVENTOS.
La privacidad de los Usuarios del Sitio es muy importante para CAGP. Toda la información que le sea recabada a los Usuarios del Sitio será procesada y tratada de conformidad con la Política de Privacidad de CAGP. Al utilizar el Sitio, Usted acepta el procesamiento y garantiza que los datos proporcionados por Usted son exactos y precisos.
PROPIEDAD INDUSTRIAL E INTELECTUAL.
CAGP así como sus empresas subsidiarias, filiales y/o relacionadas, así como sus licenciantes y licenciatarios, ostentan, ya sea por sí mismos, y/o por virtud de la celebración de algún contrato con terceros, todos los derechos sobre el contenido y diseño del Sitio y, en especial, de forma enunciativa mas no limitativa sobre las campañas, fotografías, imágenes, textos, logotipos, diseños, marcas, nombres comerciales, audios, videos, datos y software (incluido el código, interfaz y estructura del Sitio) que se incluyen en dicho Sitio. Tales derechos están protegidos por la legislación vigente y aplicable en materia de Propiedad Industrial e Intelectual.
Queda totalmente prohibida la copia, reproducción, adaptación, modificación, distribución, comercialización, comunicación pública del Sitio y/o cualquier otra acción que constituya una infracción a la legislación vigente en materia de Propiedad Industrial e Intelectual, así como el uso de los contenidos del Sitio si no es con la previa autorización expresa y por escrito de CAGP.
CAGP informa que el solo hecho de acceder y consultar el Sitio NO concede licencia, autorización o derecho implícito alguno sobre los derechos de Propiedad Intelectual e Industrial o sobre cualquier otro derecho o propiedad relacionado, directa o indirectamente, con los contenidos incluidos en el Sitio.
Zignum®, Señorío®, son marcas registradas ante el Instituto Mexicano de la Propiedad Industrial, de conformidad con la Ley de Propiedad Industrial, propiedad de CAGP, por lo que cualquier uso no autorizado de las mismas, será sancionado de conformidad con la legislación aplicable vigente.
NEGACIÓN DE GARANTÍAS Y LIMITANTES A LA RESPONSABILIDAD. 
CAGP actuará diligentemente para que el contenido del Sitio esté disponible en todo momento, sin embargo, CAGP podrá en cualquier momento y sin previo aviso interrumpir o cancelar el acceso al Sitio y/o a su contenido sin responsabilidad alguna para CAGP.
CAGP, en ningún caso será responsable por los daños y perjuicios derivados y/o relacionados con el uso del Sitio y/o su contenido, incluyendo sin limitar, la pérdida de datos, información o programas, daños a las computadoras o redes, virus. Estos Términos y Condiciones de Uso y/o el contenido del Sitio pueden contener errores y/o inexactitudes.
Existen terceras personas diferentes a CAGP y a Usted, quienes podrían llegar a tener acceso al contenido del Sitio y éstos podrían cambiar y/o eliminar dicho contenido sin la autorización de CAGP. CAGP le informa que en ningún caso será responsable en el supuesto de que dichos cambios efectuados, sin autorización de CAGP, se hagan por terceras personas que afecten el contenido del Sitio.
No hay más garantías por parte de CAGP que las que corresponden en su caso a los servicios prestados por CAGP conforme a este documento y que están expresadas en éstos Términos y Condiciones de Uso. CAGP no reconoce ni reconocerá garantías de cualquier tipo o naturaleza que no estén aquí precisadas. Ninguna información que haya sido provista por agentes o empleados de CAGP o cualquier tercero autorizado por éste o por el Sitio, podrá crear garantías de ningún tipo en relación con los Términos y Condiciones de Uso y/o el Sitio.
Los productos y en su caso servicios que se ofrecen en el Sitio son los únicos autorizados por CAGP, por lo que éste no será responsable por cualquier otro producto o en su caso servicio ofrecido por cualquier tercero distinto a CAGP.
El Sitio podrá contener grupos de discusión, grupos de noticias, tableros de noticias, salas de chat y otros servicios en los que participen terceras personas diferentes a CAGP y al Usuario. CAGP no será responsable de las comunicaciones y/o diálogos en el transcurso de los debates, foros, o chats que se organicen a través del Sitio y/o páginas de enlace, ni responderá, por tanto, de los eventuales daños y prejuicios que sufran los Usuarios a consecuencia de dichas comunicaciones o diálogos. La información que el Usuario proporcione en dichas situaciones es pública por lo que CAGP recomienda no proporcionar datos personales y/o información privada relativa a los Usuarios.
Al utilizar el Sitio, Usted acepta en forma expresa que el uso del Sitio se realiza bajo su exclusivo riesgo. El Sitio se proporciona "tal como está" y "como está disponible". Ni CAGP, ni sus afiliadas, subsidiarias y relacionadas, así como tampoco sus respectivos funcionarios, directores, empleados, agentes, proveedores de contenidos de terceros, diseñadores, contratistas, distribuidores, vendedores, patrocinadores, concedentes y demás (en lo sucesivo “Asociados”) garantizan que el uso del Sitio no sufrirá interrupciones ni contendrá errores. Además, CAGP no declara que el contenido provisto en el Sitio sea aplicable a, ni de uso apropiado en, lugares fuera de México. Ningún tipo de asesoramiento verbal ni información por escrito por parte de CAGP o sus Asociados constituirá una garantía.
Bajo ninguna circunstancia CAGP ni sus Asociados serán responsables de ningún daño directo, indirecto, imprevisto, especial ni emergente que se genere, ya sea por el uso o su falta de capacidad para usar el Sitio, incluidos de forma enunciativa más no limitativa, los daños que surjan a raíz de su confianza en la información obtenida en el Sitio que ocasione errores, omisiones, interrupciones, eliminación o corrupción de archivos, virus, demoras en la operación o transmisión, o cualquier otro tipo de error en el funcionamiento. La limitación de responsabilidad precedente se aplicará en toda acción legal, ya sea por contrato, agravio o cualquier otro reclamo, aun cuando un representante autorizado de CAGP haya sido informado o debiera tener conocimiento de la posibilidad de dichos daños. El Usuario reconoce que este párrafo se aplicará a todo contenido y en su caso servicios disponibles por medio del Sitio.
Asimismo, CAGP no será responsable si por cualquier razón el Sitio no está disponible en cualquier momento o por cualquier período.
Si a Usted se le proporciona un código de identificación de usuario, contraseña o cualquier otra pieza de información como parte de un sistema de registro o de un procedimiento de seguridad, Usted deberá tratar dicha información como confidencial, y no deberá revelarla a cualquier tercero. CAGP no será responsable, directa o indirectamente, de ninguna manera por cualquier pérdida o daño de cualquier tipo incurridos como resultado de, o en conexión con, la falta de cumplimiento con estos Términos y Condiciones de Uso. CAGP tiene el derecho de desactivar cualquier código de identificación de usuario o contraseña, ya sea elegido por Usted o asignado por CAGP, en cualquier momento, si en la opinión de CAGP, Usted ha incumplido cualquiera de las disposiciones de estos Términos y Condiciones de Uso. De vez en cuando, es posible restringir el acceso a algunas partes del Sitio, o de todo el Sitio, para los usuarios que se hayan registrado con CAGP.
SUPERVIVENCIA DE LOS TÉRMINOS Y CONDICIONES.
En el caso de que alguna autoridad judicial y/o administrativa declare la nulidad de algún inciso, párrafo o cláusula de los presentes Términos y Condiciones de Uso, los demás incisos, párrafos y cláusulas del presente instrumento continuarán siendo obligatorios para las partes.
INDEMNIZACIÓN. 
Usted reconoce y acepta que será responsable de indemnizar y sacar a paz y a salvo a CAGP, sus filiales, subsidiarias y/o cualquier sociedad relacionada corporativamente con ésta, por los daños y perjuicios derivados del incumplimiento a lo establecido en estos Términos y Condiciones de Uso, así como de los daños y perjuicios que deriven de o se relacionen con el uso indebido que Usted haga del Sitio.
ENCABEZADOS E INCISOS. 
Todos los títulos, encabezados e incisos de los presentes Términos y Condiciones de Uso se utilizan únicamente para facilitar referencias por lo que no afectarán el contenido o interpretación de los mismos.
JURISDICCIÓN Y LEY APLICABLE.
Para resolver cualquier controversia o conflicto que se derive de los presentes Términos y Condiciones de Uso, de la visita o uso del Sitio, y en su caso de aquellos relacionados con la adquisición de productos o servicios a través del Sitio, las partes se someten a las leyes aplicables de la República Mexicana y a la jurisdicción de los tribunales de la Ciudad de México, Distrito Federal, renunciando expresamente a cualquier otro fuero que pudiere corresponderles por razón de sus domicilios presentes o futuros.
Si tiene alguna duda sobre el material que aparece en el Sitio, por favor póngase en contacto por escrito para la atención de nuestro Asesor Digital en <a href="mailto:contacto@agpch.mx">contacto@agpch.mx</a>.
</p>
</section>
@show